language: python

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=pypy

install:
  - pip install tox

script: tox

branches:
  only:
    - develop
    - 1.3.X
    - 1.4.X
    - 1.5.X

notifications:
  irc: "irc.freenode.org#pip"
